### ISSUE TITLE
Allow multiple accounts

### ISSUE THREAD

**Issue by ouun** [loyaruarutoitsu/mailbox-cli#1]
@loyaruarutoitsu, thank you for the very useful package. It really helps a lot administrating accounts.
Sadly I'm not a ruby developer and therefore can not contribute by my own. However I think supporting multiple accounts would be very useful:

`bin/cli auth` could be extended by a parameter such as `bin/cli auth [username]` and saves the auth info e.g. in `.auth-[username].yml`.

Kind regards,
Philipp

**Comment by colinatkins** [comment]
@ouun Thank you for your suggestion.

Once authenticated a session id is stored in the yml file. However, its questionable how the requests made after authentication should know which account to use. Adding the username to each command is also cumbersome as it goes somewhat against the API definition. 

Cheers,
Colin

**Comment by ouun** [comment]
@loyaruarutoitsu thanks for your reply. I agree that adding the username is not a solution.
Maybe a `switch` function would be better. Let's say I do `cli auth` with users A, B & C after each other, I would be able to do `cli switch A` or `cli switch B` to switch to the other user without the need to enter the credentials again.

Kind regards,
Philipp

**Comment by colinatkins** [comment]
Thank you for your suggestion. However I am currently unable to implement something like this. Unless you make a code contribution I unfortunately have to close the issue.
